spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://117.78.60.51:3306/test4?useUnicode=true&characterEncoding=utf-8
    username: root
    password: neiwang-zhongguangzhangshi
  jpa:
    show-sql: true
server:
  port: 10011
girl:
  name: lili
  age: 11
